### ISSUE TITLE
Real-Time vs. Playback Plot Differences

### ISSUE THREAD

**Issue by AgileEngineeringLLC** [acebrianjuan/gnss-sdr-monitor#10] opened 2020-07-27 18:37 UTC
Hi,
This plotting routine is fantastic, thanks so much for sharing it!

I'm trying to understand some unusual behavior I'm seeing in GNSS-SDR-Monitor in real-time vs playback. I'm running a HackRF at 4MS/S using the conf file in this Dropbox link. I've also included the 10min data file here as well.

https://www.dropbox.com/sh/rayvktrqywu60f8/AAB_J_0s9Rf1bJ_HM4tcixa9a?dl=0

When running in real-time, I see a nice plot of Doppler with no discontinuities. Here's a sample of the real-time plot from the data collected in the above link.

![HackRF_Doppler_Realtime_072720](https://user-images.githubusercontent.com/30239895/88578057-91f31280-d00d-11ea-9180-5765410c7237.png)

However, when I play the recorded data back through GNSS-SDR, GNSS-SDR-Monitor plots the Doppler data with "jumps" or discontinuities, like the following plot shows, yet the PVT solution still seems good.

![HackRF_Doppler_Playback_072720](https://user-images.githubusercontent.com/30239895/88578146-b6e78580-d00d-11ea-984f-bc36d2cf3a1b.png)

An interesting note is that if I play the data back through SoftGNSS (Matlab), I do not see these jumps. Here's a plot of the same recorded data plotted in SoftGNSS.

![HackRF_SoftGNSS_072720](https://user-images.githubusercontent.com/30239895/88578210-ce267300-d00d-11ea-8a49-ee470acd631a.png)

Any thoughts on what might be causing the difference in Doppler plotting between real-time and playback in GNSS-SDR-Monitor?

Thanks much, great program!

Don

**Comment by acebrianjuan** [comment] 2020-07-28 00:19
Hi Don,

Are you using the `SignalSource.enable_throttle_control=false` option in your GNSS-SDR configuration file?

Based on this assumption, my initial guess is that while you play the recorded data back, GNSS-SDR sends the serialized data at a very fast rate<sup>[1](#footnote1)</sup> causing some UDP packets to be dropped<sup>[2](#footnote2)</sup>. This would explain the "jumps" you are seeing in the plots at the other end.

Try setting `SignalSource.enable_throttle_control` to `true`<sup>[3](#footnote3)</sup> and see if the "jumps" disappear when you play the recorded data back.

Let me know if this is of any help to you.

Regards,
Álvaro

---
<a name="footnote1">[1]</a>: This is because when reading data from a file, if `SignalSource.enable_throttle_control` is set to `false`, GNSS-SDR works as fast as the CPU allows.

<a name="footnote2">[2]</a>: This mostly has to do with socket buffers as explained [here](https://jvns.ca/blog/2016/08/24/find-out-where-youre-dropping-packets/), even for local inter-process communication.

<a name="footnote3">[3]</a>: Enabling this option tells the signal source to keep the delay between samples in post processing. It helps to not overload the CPU, but the processing time will be longer.

**Comment by AgileEngineeringLLC** [comment] 2020-07-28 12:39
Alvaro, Good advice thanks, that fixed it. I was thinking that throttle control only applied to real-time. Thanks! Don

**Comment by acebrianjuan** [comment] 2020-07-28 12:55
Don,

I'm glad the issue is resolved. I am closing it now.
Please feel free to reopen it or create a new one should you encounter any problems.

Regards,
Álvaro

**Closed by acebrianjuan** 2020-07-28 12:55 UTC
